CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(40) NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(160) NOT NULL,
  role ENUM('ADMIN', 'AGENT', 'DELIVERY') NOT NULL,
  commission_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(160) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(40) NOT NULL,
  address VARCHAR(500) NOT NULL,
  assigned_agent_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_customer_agent FOREIGN KEY (assigned_agent_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS import_batches (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  file_name VARCHAR(255) NOT NULL,
  uploaded_by BIGINT UNSIGNED NOT NULL,
  status ENUM('PROCESSING', 'NEEDS_REVIEW', 'CONFIRMED', 'CANCELLED', 'FAILED') NOT NULL DEFAULT 'PROCESSING',
  total_rows INT UNSIGNED NOT NULL DEFAULT 0,
  ready_rows INT UNSIGNED NOT NULL DEFAULT 0,
  attention_rows INT UNSIGNED NOT NULL DEFAULT 0,
  error_message VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmed_at TIMESTAMP NULL,
  CONSTRAINT fk_import_batch_user FOREIGN KEY (uploaded_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL UNIQUE,
  description VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  category_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(180) NOT NULL,
  sku VARCHAR(60) NOT NULL UNIQUE,
  price DECIMAL(12,2) NOT NULL,
  description TEXT NULL,
  stock_on_hand INT UNSIGNED NOT NULL DEFAULT 0,
  stock_reserved INT UNSIGNED NOT NULL DEFAULT 0,
  low_stock_threshold INT UNSIGNED NOT NULL DEFAULT 5,
  reorder_level INT UNSIGNED NOT NULL DEFAULT 10,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT chk_product_price CHECK (price > 0),
  CONSTRAINT chk_reserved_stock CHECK (stock_reserved <= stock_on_hand)
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  tracking_number VARCHAR(40) NOT NULL UNIQUE,
  customer_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NULL,
  delivery_employee_id BIGINT UNSIGNED NULL,
  delivery_assignment_version INT UNSIGNED NOT NULL DEFAULT 0,
  estimated_delivery_at DATETIME NULL,
  delivery_sla_due_at DATETIME NULL,
  sla_policy_version TINYINT NULL DEFAULT 1,
  delivery_region ENUM('BICOL','LUZON','VISAYAS','MINDANAO') NULL,
  delivery_remote_days TINYINT UNSIGNED NOT NULL DEFAULT 0,
  prepared_at DATETIME NULL,
  dispatched_at DATETIME NULL,
  delivery_sla_from_at DATETIME NULL,
  destination_latitude DECIMAL(10,7) NULL,
  destination_longitude DECIMAL(10,7) NULL,
  product_id BIGINT UNSIGNED NULL,
  quantity INT UNSIGNED NULL,
  unit_price DECIMAL(12,2) NULL,
  delivery_address VARCHAR(500) NOT NULL,
  payment_method VARCHAR(80) NOT NULL,
  payment_status ENUM('UNPAID', 'PARTIALLY_PAID', 'PAID') NOT NULL DEFAULT 'UNPAID',
  cash_received DECIMAL(12,2) NULL,
  cash_change DECIMAL(12,2) NULL,
  order_status ENUM('PENDING', 'APPROVED', 'COMPLETED', 'CANCELLED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  delivery_status ENUM('PREPARING', 'DISPATCHED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED') NULL,
  origin ENUM('LIVE', 'IMPORTED') NOT NULL DEFAULT 'LIVE',
  import_batch_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_order_agent FOREIGN KEY (agent_id) REFERENCES users(id),
  CONSTRAINT fk_order_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT fk_order_import_batch FOREIGN KEY (import_batch_id) REFERENCES import_batches(id),
  CONSTRAINT chk_order_quantity CHECK (quantity IS NULL OR quantity > 0)
);

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  unit_price DECIMAL(12,2) NOT NULL,
  product_name VARCHAR(180) NOT NULL,
  sku VARCHAR(60) NOT NULL,
  CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT chk_order_item_quantity CHECK (quantity > 0),
  CONSTRAINT chk_order_item_price CHECK (unit_price > 0)
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  type ENUM('ADD', 'DEDUCT', 'RESERVE', 'RELEASE') NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  note VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT fk_inventory_actor FOREIGN KEY (actor_id) REFERENCES users(id),
  CONSTRAINT fk_inventory_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE IF NOT EXISTS delivery_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  status ENUM('PREPARING', 'DISPATCHED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED') NOT NULL,
  notes VARCHAR(500) NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_delivery_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE IF NOT EXISTS commissions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL UNIQUE,
  agent_id BIGINT UNSIGNED NOT NULL,
  rate DECIMAL(5,2) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_commission_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_commission_agent FOREIGN KEY (agent_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS leads (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(160) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(40) NOT NULL,
  source VARCHAR(100) NOT NULL,
  assigned_agent_id BIGINT UNSIGNED NULL,
  status ENUM('NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'LOST') NOT NULL DEFAULT 'NEW',
  converted_customer_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_lead_agent FOREIGN KEY (assigned_agent_id) REFERENCES users(id),
  CONSTRAINT fk_lead_customer FOREIGN KEY (converted_customer_id) REFERENCES customers(id)
);

CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(180) NOT NULL UNIQUE,
  target_audience VARCHAR(500) NOT NULL,
  content TEXT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status ENUM('DRAFT', 'SCHEDULED', 'ACTIVE', 'COMPLETED') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT chk_campaign_dates CHECK (end_date > start_date)
);

CREATE TABLE IF NOT EXISTS order_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  actor_id BIGINT UNSIGNED NULL,
  type VARCHAR(40) NOT NULL,
  message VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_event_order FOREIGN KEY (order_id) REFERENCES orders(id),
  CONSTRAINT fk_order_event_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS import_rows (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  batch_id BIGINT UNSIGNED NOT NULL,
  sheet_name VARCHAR(60) NOT NULL,
  section ENUM('STORE_SALES', 'HOME_CREDIT', 'CI_AGENT', 'CI_PAYMENT') NOT NULL,
  row_no INT UNSIGNED NOT NULL,
  order_date DATE NOT NULL,
  raw_customer_name VARCHAR(255) NULL,
  raw_product_name VARCHAR(255) NULL,
  raw_agent_name VARCHAR(255) NULL,
  raw_imei VARCHAR(255) NULL,
  raw_note VARCHAR(255) NULL,
  raw_or_no VARCHAR(60) NULL,
  unit_price DECIMAL(12,2) NULL,
  cash_received DECIMAL(12,2) NULL,
  payment_status ENUM('PARTIALLY_PAID', 'PAID') NOT NULL DEFAULT 'PAID',
  payment_method VARCHAR(80) NOT NULL DEFAULT 'Cash',
  customer_id BIGINT UNSIGNED NULL,
  new_customer_name VARCHAR(160) NULL,
  product_id BIGINT UNSIGNED NULL,
  new_product_name VARCHAR(180) NULL,
  agent_id BIGINT UNSIGNED NULL,
  status ENUM('READY', 'NEEDS_ATTENTION', 'SKIPPED') NOT NULL DEFAULT 'READY',
  issue VARCHAR(255) NULL,
  created_order_id BIGINT UNSIGNED NULL,
  CONSTRAINT fk_import_row_batch FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE,
  CONSTRAINT fk_import_row_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
  CONSTRAINT fk_import_row_product FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT fk_import_row_agent FOREIGN KEY (agent_id) REFERENCES users(id),
  CONSTRAINT fk_import_row_order FOREIGN KEY (created_order_id) REFERENCES orders(id),
  CONSTRAINT chk_import_row_price CHECK (unit_price IS NULL OR unit_price > 0)
);
